Repository pagopa/pagopa-gpd-upload, pull requests merged in 2025-09, with the labels that each got.

#53 chore: [PAGOPA-3216] Identity
  .github/workflows/integration_test.yml
  .github/workflows/release_deploy.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
Labels: size/small

#55 fix: Get status or report for old upload statuses without serviceType
  src/main/java/it/gov/pagopa/gpd/upload/service/StatusService.java
Labels: size/small, patch

#58 fix: GHA release & deploy skip not working
  .github/workflows/release_deploy.yml
Labels: size/small, skip

#61 [PagoPA-3282] - Get fileID list
  openapi/openapi-internal-support.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
  pom.xml
  src/main/java/it/gov/pagopa/gpd/upload/controller/external/v1/CheckUploadController.java
  src/main/java/it/gov/pagopa/gpd/upload/controller/external/v2/CheckUploadController.java
  src/main/java/it/gov/pagopa/gpd/upload/model/FileIdListResponse.java
  src/main/java/it/gov/pagopa/gpd/upload/repository/StatusRepository.java
  src/main/java/it/gov/pagopa/gpd/upload/service/StatusService.java
  src/main/java/it/gov/pagopa/gpd/upload/utils/CommonCheck.java
  src/test/java/it/gov/pagopa/gpd/upload/controller/v1/CheckUploadControllerTest.java
  src/test/java/it/gov/pagopa/gpd/upload/controller/v2/CheckUploadControllerTest.java
  src/test/java/it/gov/pagopa/gpd/upload/service/StatusServiceTest.java
Labels: size/large, minor

#56 feat: [PAGOPA-3280] Add operationStatus property to getUpdateStatus response
  openapi/openapi-internal-support.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
  src/main/java/it/gov/pagopa/gpd/upload/controller/external/v1/CheckUploadController.java
  src/main/java/it/gov/pagopa/gpd/upload/controller/external/v2/CheckUploadController.java
  src/main/java/it/gov/pagopa/gpd/upload/model/UploadStatus.java
  src/main/java/it/gov/pagopa/gpd/upload/model/v2/UploadStatusV2.java
  src/main/java/it/gov/pagopa/gpd/upload/model/v2/enumeration/OperationStatus.java
  src/main/java/it/gov/pagopa/gpd/upload/service/StatusService.java
Labels: size/large, minor

#62 feat: [PAGOPA-3281] Report v2
  openapi/openapi-internal-support.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
  pom.xml
  src/main/java/it/gov/pagopa/gpd/upload/config/JacksonFactory.java
  src/main/java/it/gov/pagopa/gpd/upload/controller/external/v1/CheckUploadController.java
  src/main/java/it/gov/pagopa/gpd/upload/controller/external/v2/CheckUploadController.java
  src/main/java/it/gov/pagopa/gpd/upload/controller/support/SupportController.java
  src/main/java/it/gov/pagopa/gpd/upload/model/FileIdListResponse.java
  src/main/java/it/gov/pagopa/gpd/upload/model/v1/UploadReport.java
  src/main/java/it/gov/pagopa/gpd/upload/model/v1/UploadStatus.java
  src/main/java/it/gov/pagopa/gpd/upload/model/v2/ResponseEntryDTO.java
  src/main/java/it/gov/pagopa/gpd/upload/model/v2/UploadReportDTO.java
  src/main/java/it/gov/pagopa/gpd/upload/model/v2/UploadStatusDTO.java
  src/main/java/it/gov/pagopa/gpd/upload/model/v2/UploadStatusV2.java
  src/main/java/it/gov/pagopa/gpd/upload/repository/StatusRepository.java
  src/main/java/it/gov/pagopa/gpd/upload/service/BlobService.java
  src/main/java/it/gov/pagopa/gpd/upload/service/StatusService.java
  src/main/java/it/gov/pagopa/gpd/upload/utils/ResponseEntryDTOMapper.java
  src/test/java/it/gov/pagopa/gpd/upload/controller/SupportControllerTest.java
  src/test/java/it/gov/pagopa/gpd/upload/controller/v1/FileUploadControllerTest.java
  src/test/java/it/gov/pagopa/gpd/upload/controller/v2/FileUploadControllerTest.java
  src/test/java/it/gov/pagopa/gpd/upload/service/StatusServiceTest.java
  src/test/resources/application.properties
Labels: enhancement, size/large
