Repository pagopa/pagopa-gpd-upload, pull requests merged in 2025-10, with the labels that each got.

#67 fix: Generated openapi
  openapi/openapi-internal-support.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
Labels: size/large, skip

#69 feat: [PIDM-504] update deploy config and strategy
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, minor

#71 chore: Opex
  .github/workflows/create_dashboard.yaml
  .opex/gpd-upload/env/prod/config.yaml
  .opex/gpd-upload/env/uat/backend.ini
  .opex/gpd-upload/env/uat/backend.tfvars
  .opex/gpd-upload/env/uat/config.yaml
  .opex/gpd-upload/v1/env/prod/backend.ini
  .opex/gpd-upload/v1/env/prod/backend.tfvars
  .opex/gpd-upload/v1/env/prod/config.yaml
  .opex/gpd-upload/v1/env/prod/terraform.tfvars
  .opex/gpd-upload/v2/env/prod/backend.ini
  .opex/gpd-upload/v2/env/prod/backend.tfvars
  .opex/gpd-upload/v2/env/prod/config.yaml
  .opex/gpd-upload/v2/env/prod/terraform.tfvars
Labels: size/small, skip

#72 chore: [PAGOPA-3283] Monitoring
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi-internal-support.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
  pom.xml
  src/main/java/it/gov/pagopa/gpd/upload/controller/support/SupportController.java
  src/main/java/it/gov/pagopa/gpd/upload/repository/StatusRepository.java
  src/main/java/it/gov/pagopa/gpd/upload/service/SlackService.java
  src/main/java/it/gov/pagopa/gpd/upload/service/StatusService.java
  src/main/java/it/gov/pagopa/gpd/upload/service/SupportService.java
  src/main/java/it/gov/pagopa/gpd/upload/utils/CommonCheck.java
  src/main/java/it/gov/pagopa/gpd/upload/utils/SlackNotifier.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/gpd/upload/controller/SupportControllerTest.java
  src/test/java/it/gov/pagopa/gpd/upload/service/RecoveryServiceTest.java
  src/test/java/it/gov/pagopa/gpd/upload/service/SlackServiceTest.java
  src/test/java/it/gov/pagopa/gpd/upload/service/SupportServiceGroupingTest.java
  src/test/java/it/gov/pagopa/gpd/upload/service/SupportServiceTest.java
  src/test/java/it/gov/pagopa/gpd/upload/utils/SlackNotifierTest.java
  src/test/java/it/gov/pagopa/gpd/upload/utils/TestMockFactory.java
Labels: size/large, patch
