Repository pagopa/pagopa-gpd-upload, pull requests merged in 2025-05, with the labels that each got.

#44 fix: [PIDM-491]: jdk update
  .github/workflows/update_code.yml
Labels: size/small, skip

#42 chore: [PIDM-491] Implement workload identity
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/integration_test.yml
  .github/workflows/release_deploy.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .identity/99_main.tf
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: skip

#46 [PAGOPA-2426] fix(unzip): Use ByteArrayOutputStream instead of FileOutputStream
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi-support-internal.json
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/gpd/upload/service/BlobService.java
Labels: size/small
